### ISSUE TITLE
Where's awesomeness?

### ISSUE THREAD

**Issue by pfalcon** [pombredanne/awesome-succint-data-structures#1]
Subj ;-)

**Comment by pombredanne** [comment]
@pfalcon :D I created the repo, but the list still needs to be written! PRs welcomed!

**Comment by pfalcon** [comment]
Let's compete then: https://github.com/pfalcon/awesome-implicit-data-structures ;-). (As the name suggest, I'd like to enumerate implicit data structures first of all.)

**Comment by pombredanne** [comment]
And you got me started: https://github.com/pombredanne/awesome-succint-data-structures/blob/master/README.md ... I do not want to compete FWIW, and I would rather contribute to yours ;)

**Comment by pombredanne** [comment]
You like the name implicit better than succinct?

**Comment by pombredanne** [comment]
and FWIW, I am a modest Pythonista, so you are from what I can see with your micropython work... so in anycase let's join forces!

**Comment by pfalcon** [comment]
Then I'd rather keep myself to implicit data structures and link/contribute to yours.

> You like the name implicit better than succinct?

Well, I'm not a specialist in the area, and started with very pragmatic needs - looking how to support item deletion from a binary heap in time better than O(n), came across beaps, then thought they could be useful to implement dictionaries too after all, which got me looking beyond that to see what's more available (e.g. succinct structures). But that quickly gets specialized and beyond my immediate interest, so I don't think I'd realistically maintain a list of those...

**Comment by pfalcon** [comment]
> micropython work

Yes, it exactly comes from that - need to support task unscheduling in a asyncio-like coroutine scheduler, then MicroPython uses hashtables for dictionaries, but with load factors close to 1, which makes them O(n) effectively... No interests beyond that so far ;-).

**Comment by pfalcon** [comment]
Added the link in https://github.com/pfalcon/awesome-implicit-data-structures/commit/7f198c46f03d4c01ed6e6d74d8555efc0bb40fed , thanks!
